### ISSUE TITLE
resources/lib/color.lua uses lua 5.3+ idiv which is not supported by luajit

### ISSUE THREAD

**Issue by incompetentcoder** [nullstare/ReiLua#2]
As the title says, trying to run any raygui examples or ReiLuaGui examples with luajit fails due to the color.lua file in line 33 using // for idiv, changing it to  return Color:new( math.floor(c.r / v), math.floor(c.g / v), math.floor(c.b / v), math.floor(c.a / v)) makes it work with luajit 5.1/5.2

**Comment by nullstare** [comment]
Thanks for reporting. Yeah I will just remove those since I don't see them that useful. Already removed from the other ones.
